Repository Alfresco/acs-packaging, pull requests merged in 2020-09, with the labels that each got.

#1666 APPS-166: added latest image for share
  tests/pipeline-all-amps/share/pom.xml
Labels: PR: reviewed-approved

#1668 MNT-21875 : [PaaS] Alfresco Content Services 7.0.0 M1 Distribution contains invalid Keystore
  distribution/pom.xml
Labels: PR: reviewed-approved

#1686 MNT-21859 Embed old keystore in docker images
  .travis.yml
  docker-alfresco/Dockerfile
  docker-alfresco/aws/pom.xml
  docker-alfresco/pom.xml
  pom.xml
  tests/environment/docker-compose-aims.yml
  tests/environment/docker-compose-all-amps-test.yml
  tests/environment/docker-compose-cluster.yml
  tests/environment/docker-compose-cmis-tests.yml
  tests/environment/docker-compose-email-tests.yml
  tests/environment/docker-compose-integration-tests.yml
  tests/environment/docker-compose-minimal.yml
  tests/environment/docker-compose-node-restart.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/environment/docker-compose-rest-api-tests.yml
  tests/environment/docker-compose-sync-service.yml
  tests/environment/docker-compose-with-ldap.yml
Labels: PR: partially-approved

#1691 ACS-644: S3 Connector 3.1.0 Final Release
  pom.xml
Labels: PR: reviewed-approved

#1693 ACS-646: Update Glacier Connector to 2.1.0
  pom.xml
Labels: PR: reviewed-approved

#1701 APPS-403 updated AGS version
  pom.xml
Labels: PR: partially-approved

#1702 ATS-825 : Updated T-engines to 2.3.5
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#1703 ATS-825 : Updated T-engines to 2.3.5
  tests/environment/.env
Labels: PR: unreviewed

#1712 MNT-21766 - Bump dependencies
  pom.xml
Labels: PR: unreviewed

#1715 MNT-21732 Update alfresco-repository to include metadata endpoint fix.
  pom.xml
Labels: PR: reviewed-approved

#1717 MNT-21800 : Pick upstream dependencies
  pom.xml
Labels: PR: reviewed-approved

#1716 MNT-21800 : Pick upstream dependencies
  pom.xml
Labels: PR: reviewed-approved

#1718 MNT-21800 : Pick upstream dependencies
  pom.xml
Labels: PR: reviewed-approved
