Repository Alfresco/acs-packaging, pull requests merged in 2020-12, with the labels that each got.

#1797 ACS-857 : Azure Connector 1.2 Alpha Release to 6.2.N
  pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: partially-approved

#1799 ACS-960 Disable very frequent intermittent test failures
  tests/tas-email/src/test/java/org/alfresco/email/imap/ImapReadMessagesAscTests.java
Labels: PR: reviewed-approved

#1796 ACS-857 : Azure Connector 1.2 Alpha Release to master
  pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: partially-approved

#1802 bumpo of share to A13
  pom.xml
Labels: PR: partially-approved

#1806 ACS-857 : Azure Connector 1.2 Alpha Release
  .travis.yml
  pom.xml
Labels: PR: partially-approved

#1810 upgrade of AGS to version 3.5.0-A1
  pom.xml
Labels: PR: partially-approved

#1807 ACS-857 : Azure Connector 1.2 Alpha Release
  pom.xml
Labels: PR: reviewed-approved

#1811 bump to Share A14
  pom.xml
Labels: PR: unreviewed

#1805 ACS-999 Run ACS on docker with a configurable set of AMPs
  .travis.yml
  tests/pipeline-all-amps/README.md
  tests/pipeline-all-amps/Readme.md
  tests/pipeline-all-amps/pom.xml
  tests/pipeline-all-amps/repo/Dockerfile
  tests/pipeline-all-amps/repo/docker-entrypoint.sh
  tests/pipeline-all-amps/repo/pom.xml
  tests/pipeline-all-amps/repo/run.sh
  tests/pipeline-all-amps/share/Dockerfile
  tests/pipeline-all-amps/share/docker-entrypoint.sh
  tests/pipeline-all-amps/share/pom.xml
  tests/pipeline-all-amps/share/run.sh
Labels: PR: unreviewed

#1813 bump to AGS 350 A2
  pom.xml
Labels: PR: partially-approved

#1814 ACS-1016 : Azure Connector 1.2.0 Final Release
  pom.xml
Labels: PR: reviewed-approved

#1815 ACS-1016 : Azure Connector 1.2.0 Final Release
  pom.xml
Labels: PR: reviewed-approved

#1816 Update AGS version with 3.5.0-M1
  pom.xml
Labels: PR: reviewed-approved

#1817 bump to share 7.0.0-M3
  pom.xml
Labels: PR: unreviewed

#1820 fix share pipeline all amps image exception startup
  tests/pipeline-all-amps/share/Dockerfile
Labels: PR: unreviewed

#1819 Bump sync service from 3.3.3.1 to 3.4.0-M2
  pom.xml
  tests/environment/.env
Labels: PR: reviewed-approved

#1812 SEARCH-2554 Add ElasticSearch search tests
  .travis.yml
  tests/environment/.env
  tests/environment/docker-compose-elasticsearch.yml
  tests/pom.xml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
  tests/tas-elasticsearch/src/test/resources/alfresco-elasticsearch-context.xml
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: unreviewed

#1821 OPSEXP-675: Add API Explorer back into pipeline-all-amps
  tests/pipeline-all-amps/repo/Dockerfile
  tests/pipeline-all-amps/repo/pom.xml
Labels: PR: unreviewed

#1822 SEARCH-2577 remove direct dependency from ES client, update ES image …
  tests/environment/.env
  tests/tas-elasticsearch/pom.xml
Labels: PR: reviewed-approved
