Repository Alfresco/acs-packaging, pull requests merged in 2020-10, with the labels that each got.

#1720 APPS-541: [AOS] Upgrade for ACS 7 compatibility
  pom.xml
Labels: PR: partially-approved

#1721 APPS-860 update dependencies
  pom.xml
Labels: PR: unreviewed

#1731 APPS-542: Bump AOS to 1.4.0-M1
  pom.xml
Labels: PR: reviewed-approved

#1722 MNT-21871 : [Security] Multiple jackson-databind vulnerabilities
  pom.xml
Labels: PR: unreviewed

#1705 ACS-525: org.alfresco.surf:spring-webscripts:8.8 & acs-packaging test failure
  pom.xml
  tests/tas-integration/src/test/java/org/alfresco/tas/integration/IntegrationWithWebScriptsTests.java
Labels: PR: reviewed-approved

#1740 Merge changes on support/SP/6.2.N (6.2.3-A1) since 15/7/2020 16:22 to release/6.2.N
  .travis.yml
  dev/aliases
  dev/cherry-pick-old-projects-setup.sh
  dev/docker-compose.yml
  distribution/pom.xml
  distribution/src/main/resources/README.txt
  distribution/src/main/resources/VERSIONS.md
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: unreviewed

#1752 MNT-21871: Revert jackson-databind from 2.11.2 back to 2.10.1
  pom.xml
Labels: PR: unreviewed

#1742 MNT-21871 : [Security] Multiple jackson-databind vulnerabilities
  pom.xml
Labels: PR: unreviewed

#1773 APPS-553: Share version 7.0.0-M2 doesn't display the correct version
  pom.xml
Labels: PR: partially-approved

#1778 APPS-553: Share version 7.0.0-M2 doesn't display the correct version
  pom.xml
Labels: PR: partially-approved

#1780 APPS-595 : Changes from MNT-20195 break Travis build for alfresco-community-repo
  pom.xml
Labels: PR: partially-approved
