Repository Alfresco/acs-packaging, pull requests merged in 2020-11, with the labels that each got.

#1782 SEARCH-2535 Remove MM from tests
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: unreviewed

#1783 ACS-765 - Removed the Cluster test
  .travis.yml
  tests/pom.xml
  tests/tas-cluster/pom.xml
  tests/tas-cluster/src/test/java/org/alfresco/rest/ClusterProperties.java
  tests/tas-cluster/src/test/java/org/alfresco/rest/ClusterTest.java
  tests/tas-cluster/src/test/java/org/alfresco/rest/cluster/ModelReloadTests.java
  tests/tas-cluster/src/test/resources/alfresco-cluster-context.xml
  tests/tas-cluster/src/test/resources/default.properties
  tests/tas-cluster/src/test/resources/log4j.properties
  tests/tas-cluster/src/test/resources/restapi-cluster-suite.xml
  tests/tas-cluster/src/test/resources/shared-resources/testdata/hugeDataModel.xml
  tests/tas-cluster/src/test/resources/shared-resources/testdata/test-model.xml
Labels: PR: reviewed-approved

#1784 Delete docker-compose-cluster.yml
  tests/environment/docker-compose-cluster.yml
Labels: PR: unreviewed

#1785 ACS-766: Removing Restart nodes test
  .travis.yml
  tests/environment/docker-compose-node-restart.yml
  tests/scripts/node-restart-test.sh
Labels: PR: partially-approved

#1786 ACS-741 : SAML - Logout is not working on Chrome
  pom.xml
Labels: PR: partially-approved

#1789 MNT-18497 : Displaying Folder With Many Linked Nodes is Slow in Share
  pom.xml
Labels: PR: partially-approved

#1790 [ACS-727] run tas-cmis tests on all 3 bindings
  .travis.yml
  tests/tas-cmis/pom.xml
  tests/tas-cmis/src/test/resources/aims-environment.properties
  tests/tas-cmis/src/test/resources/default.properties
Labels: PR: unreviewed

#1792 ACS-265: Make TAS test run in the single pipeline
  tests/pipeline-all-amps/repo/Dockerfile
Labels: PR: partially-approved

#1793 PRODDEL-4373-salesforce-bump to version 2.2.1-M1
  pom.xml
Labels: PR: partially-approved

#1795 Feature/repo 5353 accelerated search feature documentation - first draft
  docs/images/RefreshQuerySet1.png
  docs/images/RefreshQuerySet2.png
  docs/images/RefreshQuerySetNotStarted.png
  docs/images/RefreshQuerySetStarted.png
  docs/query-accelerator.md
Labels: PR: reviewed-approved

#1798 bump to share A12
  pom.xml
Labels: PR: reviewed-approved
