Repository Alfresco/acs-packaging, pull requests merged in 2021-04, with the labels that each got.

#1919 [release][publish] HF version 6.2.2.15
  .travis.yml
  CHANGELOG.md
Labels: PR: reviewed-approved

#1923 OPSEXP-809: Upgrade DTAS to 1.0.1
  .travis.yml
  tests/pipeline-all-amps/repo/dtas/dtas-config.json
Labels: PR: reviewed-approved

#1925 SEARCH-2748 test include parameter
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: unreviewed

#1927 ACS-1489 : S3 Connector 3.1.0.2
  pom.xml
Labels: PR: reviewed-approved

#1926 ACS-1488 / ACS-1490: S3Connector 4.0.0.1 and AzureConnector 2.0.0.1 HF releases
  pom.xml
Labels: PR: partially-approved
