Repository Alfresco/acs-packaging, pull requests merged in 2021-03, with the labels that each got.

#1894 Updated AGS version to 3.5.0-A5
  pom.xml
Labels: PR: reviewed-approved

#1895 SEARCH-2707 add a test to verify that the system is able to index and search for dates before 1970
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: reviewed-approved

#1896 Bump Sync Service to 3.4.0-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#1897 ACS-1312: Azure Connector 2.0: Classpath conflict
  pom.xml
Labels: PR: unreviewed

#1899 feature/APPS-update-share-dependency: Removed share suffix from pom
  pom.xml
Labels: PR: unreviewed

#1904 APPS-801 Update AGS to version 3.5.0
  pom.xml
Labels: PR: partially-approved

#1903 DESKTOPAPP-592: Bump Sync Service version to 3.4.0 for release
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: unreviewed

#1905 ATS-876 Update ATS / T-Engine / SFS versions
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#1906 Update of Supported Office Versions
  distribution/src/main/resources/VERSIONS.md
Labels: PR: reviewed-approved

#1908 Remove DTE from VERSIONS.md as it will not initially be available with ACS 7.0.0
  pom.xml
Labels: PR: unreviewed

#1907 ACS-1233: Azure Connector 2.0.0 Final Release
  pom.xml
Labels: PR: partially-approved

#1909 ATS-875 Bump AIS to 1.3.0
  pom.xml
Labels: PR: reviewed-approved

#1910 Remove Outlook from VERSIONS.md as it will not initially be available with ACS 7.0.0
  distribution/src/main/resources/VERSIONS.md
  pom.xml
Labels: PR: unreviewed

#1912 prepare HF 6.2.2.13
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#1913 MNT-22206 - Prepare for 6.1.1.9 release
  .travis.yml
Labels: PR: unreviewed

#1916 Prepare for release 6.2.2.14
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed
