Repository Alfresco/acs-packaging, pull requests merged in 2021-08, with the labels that each got.

#2032 APPS-1068 [AGS] Publish AGS-specific docker images from acs-packaging
  docker-alfresco/ags/Dockerfile
  docker-alfresco/ags/pom.xml
  docker-share/ags/Dockerfile
  docker-share/ags/pom.xml
  pom.xml
Labels: PR: unreviewed

#2043 SEARCH-3005 Simple test for Elasticsearch with HTTP Basic Authentication
  .travis.yml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializerESBasicAuth.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchBasicAuthTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
  tests/tas-elasticsearch/src/test/resources/log4j.properties
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-basic-auth-suite.xml
Labels: PR: reviewed-approved

#2051 [AGS] Publish AGS-specific docker images from acs-packaging
  docker-alfresco/ags/Dockerfile
  docker-alfresco/ags/pom.xml
  docker-share/ags/Dockerfile
  docker-share/ags/pom.xml
  pom.xml
Labels: PR: partially-approved

#2053 SEARCH-2976 Avoid overwriting "latest" Docker Images for "release" br…
  .travis.yml
  docker-alfresco/Dockerfile
  docker-alfresco/pom.xml
  docker-share/Dockerfile
  docker-share/pom.xml
Labels: PR: partially-approved

#2054 SEARCH-2976 Avoid overwriting "latest" Docker Images for "release" br…
  .travis.yml
  docker-alfresco/Dockerfile
  docker-alfresco/pom.xml
Labels: PR: unreviewed

#2055 SEARCH-2976 Avoid overwriting "latest" Docker Images for "release" br…
  .travis.yml
  docker-alfresco/Dockerfile
  docker-alfresco/pom.xml
Labels: PR: unreviewed

#2056 DESKTOPAPP-721:Bump Sync-service from 3.4.0 to 3.4.1-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2059 Fix/search 3043 esc tests failing
  .travis.yml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/resources/testcontainers.properties
Labels: PR: reviewed-approved
