Repository Alfresco/acs-packaging, pull requests merged in 2021-06, with the labels that each got.

#1979 bump of share 7.0.1-A1
  pom.xml
Labels: PR: partially-approved

#1981 Feature/ats 936 bump t core 250
  dev/docker-compose.yml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#1976 APPS-1028 Build&publish an AGS distribution zip during the ACS release
  .travis.yml
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
  distribution-ags/pom.xml
  distribution-ags/src/assemble/ags-distribution.xml
  distribution-share/pom.xml
  pom.xml
  scripts/travis/copy_ags_to_release_bucket.sh
  scripts/travis/copy_share_to_release_bucket.sh
Labels: PR: partially-approved

#1993 ACS-1709 Include Share's Google AMP in the tomcat dev env
  dev/dev-share-amps-overlay/pom.xml
Labels: PR: reviewed-approved

#1992 ACS-1710 Let repo developers build the project without having to build AGS first.
  dev/aliases
  pom.xml
  scripts/travis/build.sh
  scripts/travis/maven_release.sh
Labels: PR: reviewed-approved

#2000 Add script to enable changing between versions of acs projects.
  dev/checkout.sh
Labels: PR: reviewed-approved

#2003 update share version 7.0.1-A4
  pom.xml
Labels: PR: partially-approved

#2004 SEARCH-2876 Update Solr 2.0.2-RC1
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
Labels: PR: unreviewed

#2005 SEARCH-2876 Update Solr 2.0.2-RC1
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
Labels: PR: unreviewed

#1999 OPSEXP-841 upgrade to DTAS 1.1
  .travis.yml
  tests/pipeline-all-amps/repo/Dockerfile
  tests/pipeline-all-amps/repo/pom.xml
Labels: PR: partially-approved

#2006 SEARCH-2952 Fix reindexing tests
  .travis.yml
  tests/environment/.env
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
Labels: PR: reviewed-approved

#2008 bump share 7.0.1-A5
  pom.xml
Labels: PR: unreviewed

#2011 ACS-1578: Release SAML module 1.2.2-A1
  pom.xml
Labels: PR: partially-approved
