Repository Alfresco/acs-packaging, pull requests merged in 2021-12, with the labels that each got.

#2126 ATS-969 - Mention Tika upgrade in the CHANGELOG
  CHANGELOG.md
Labels: PR: reviewed-approved

#2128 Depend on the configured python version instead of the os dependant one
  .travis.yml
Labels: PR: unreviewed

#2129 ACS-2201 [release] 7.2.0-A9
  .travis.yml
Labels: PR: reviewed-approved

#2130 Depend on the configured python version instead of the os dependant o…
  .travis.yml
Labels: PR: unreviewed

#2132 ACS-2331: Bump to S3 Connector 5.0.0-A4
  pom.xml
Labels: PR: unreviewed

#2133 Depend on the configured python version instead of the os dependant o…
  .travis.yml
Labels: PR: unreviewed

#2131 ACS-2264 - ES proximity search
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchProximitySearchTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
Labels: PR: unreviewed

#2135 ACS-2396: Bump ACS Packaging for cloud storage connectors
  pom.xml
Labels: PR: partially-approved
