Repository Alfresco/acs-packaging, pull requests merged in 2021-02, with the labels that each got.

#1858 [REPO-5543] Query Accelerator documentation update in regards to logging
  docs/query-accelerator.md
Labels: PR: reviewed-approved

#1854 DESKTOPAPP-539 Align Sync Service AMP version with the Camel upgrades
  .travis.yml
  docker-alfresco/pom.xml
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/environment/docker-compose-sync-service.yml
Labels: PR: unreviewed

#1862 OPSEXP-718: Use DTAS for smoke testing the pipeline-all-amps-repo image
  .travis.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/pipeline-all-amps/repo/dtas/dtas-config.json
  tests/pipeline-all-amps/repo/pom.xml
Labels: PR: reviewed-approved

#1863 Bump api-explorer A4
  pom.xml
Labels: PR: unreviewed

#1865 Prepare release 6.2.2.11 [skip ci]
  .travis.yml
Labels: PR: unreviewed

#1866 [REPO-5550] Update the documentation in regards to auditable properties
  docs/images/acs-aspects.png
  docs/images/acs-properties.png
  docs/query-accelerator.md
Labels: PR: unreviewed

#1864 Feature/repo 5538 docs for do not drop qs table
  docs/images/AdminConsoleMenu.png
  docs/images/QuerySetNotRemoved.png
  docs/images/QuerySetRemoved.png
  docs/images/RefreshQuerySet.png
  docs/images/RefreshQuerySet1.png
  docs/images/RefreshQuerySet2.png
  docs/images/RemoveQuerySet.png
  docs/query-accelerator.md
Labels: PR: partially-approved

#1867 SEARCH-2688 Elasticsearch admin console tests.
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchAdminConsoleTests.java
Labels: PR: reviewed-approved

#1870 SEARCH-2615 use a custom index name in tests
  tests/environment/docker-compose-elasticsearch.yml
Labels: PR: reviewed-approved

#1869 ACS-1232 Update Azure Connector to 2.0-A2
  pom.xml
Labels: PR: unreviewed

#1871 ACS-1230 Update S3 Connector to 4.0.0-A2
  pom.xml
Labels: PR: unreviewed

#1872 ACS-1185 Update activemq images to 5.16.1
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#1874 Updated AGS version to 3.5.0-A4
  pom.xml
Labels: PR: reviewed-approved

#1875 Feature/apps 703 bumps share and salesforce
  pom.xml
Labels: PR: unreviewed

#1877 release/APPS-share: [release] share A17
  pom.xml
Labels: PR: partially-approved

#1881 ACS-1265 Update ActiveMQ broker URLs to use NIO
  tests/environment/docker-compose-aims.yml
  tests/environment/docker-compose-all-amps-test.yml
  tests/environment/docker-compose-cmis-tests.yml
  tests/environment/docker-compose-email-tests.yml
  tests/environment/docker-compose-integration-tests.yml
  tests/environment/docker-compose-minimal.yml
  tests/environment/docker-compose-rest-api-tests.yml
  tests/environment/docker-compose-sync-service.yml
  tests/environment/docker-compose-with-ldap.yml
Labels: PR: reviewed-approved

#1873 REPO-5583 Update docs for owner and noderef
  docs/query-accelerator.md
Labels: PR: reviewed-approved

#1882 Fixed query set example, introduced brief explanation
  docs/query-accelerator.md
Labels: PR: unreviewed

#1883 ATS-852 Update ais to 1.3.0-A1
  pom.xml
Labels: PR: reviewed-approved

#1887 SEARCH-2728 change test content value because now we are doing a different analysis on camel case and the old test doesn't
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: reviewed-approved

#1888 ACS-1183 ACS 7 Stacks: PostgreSQL
  .gitbugtraq
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#1884 Bump api-explorer from 7.0.0-A4 to 7.0.0-A5
  pom.xml
Labels: PR: unreviewed

#1885 feature/APPS-update-share: to A18 on acs packaging
  pom.xml
Labels: PR: partially-approved

#1886 ACS-946 exclude meta-info folder from distribution
  distribution/src/assembly/distribution.xml
Labels: PR: reviewed-approved

#1889 No need to reference community version in acs-packaging as enterprise specifies it
  pom.xml
  scripts/travis/build.sh
  scripts/travis/build_functions.sh
Labels: PR: unreviewed

#1890 ATS-869 Upgrade ais to 1.3.0-A2
  pom.xml
Labels: PR: reviewed-approved

#1891 Bump Share from 7.0.0-A18 to 7.0.0-A19
  pom.xml
Labels: PR: partially-approved
