Repository Alfresco/acs-packaging, pull requests merged in 2021-07, with the labels that each got.

#2014 Use LF for Dockerfile(s) and .sh scripts (.gitattributes) [skip ci]
  .gitattributes
Labels: PR: partially-approved

#2017 Update share version 7.0.1
  pom.xml
Labels: PR: partially-approved

#2019 SEARCH-2878 Update the supported versions in ACS Packaging
  tests/environment/.env
Labels: PR: reviewed-approved

#2022 DESKTOPAPP-707: Bump Sync service from 3.3.4-M2 to 3.3.4.1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2018 SEARCH-2878 Update the supported SearchService version
  tests/environment/.env
Labels: PR: unreviewed

#2025 ACS-1822/ACS-1820 ACS 7.1 Supported Platforms: PostgreSQL 13.3, 12.7, 11.12 / MariaDB 10.6
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  scripts/travis/build.sh
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2028 ATS-952: bump T-engines to version 2.5.2
  dev/docker-compose.yml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2036 MNT-22511 - Prepare release 7.0.0.2
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2037 MNT-22511 - Prepare release 6.2.2.18
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2038 MNT-22511 - Prepare release 6.1.1.10
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2042 MNT-22511 - Prepare release 6.0.1.8
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2041 MNT-22511 - Prepare release 7.0.1.1
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2033 Fix intermittent failing ES e2e tests
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchAdminConsoleTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/resources/log4j.properties
Labels: PR: unreviewed

#2044 Update upstream version to 6.56.15.307
  pom.xml
Labels: PR: unreviewed

#2045 Update upstream version to 9.41
  pom.xml
Labels: PR: unreviewed

#2046 Prepare release 6.0.1.9
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed

#2047 Prepare release
  .travis.yml
  CHANGELOG.md
Labels: PR: unreviewed
