Repository Alfresco/acs-packaging, pull requests merged in 2021-01, with the labels that each got.

#1824 ACS-1033 Fix branch builds with SNAPSHOT dependencies (ACS-999 fallout)
  .travis.yml
Labels: PR: partially-approved

#1825 REPO-5203 Remove legacy transformers
  CHANGELOG.md
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j.properties
  dev/docker-compose.yml
  distribution/pom.xml
  distribution/src/assembly/distribution.xml
  distribution/src/main/resources/VERSIONS.md
  docs/creating-a-t-engine.md
  docs/custom-transforms-and-renditions.md
  docs/migrating-a-legacy-transformer.md
  pom.xml
  tests/environment/docker-compose-cmis-tests.yml
  tests/environment/docker-compose-elasticsearch.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/environment/docker-compose-rest-api-tests.yml
  tests/environment/docker-compose-with-ldap.yml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: unreviewed

#1829 ACS-1077 push pipeline images in install phase
  tests/pipeline-all-amps/pom.xml
Labels: PR: partially-approved

#1826 REPO-5191 Document how to create a custom metadata extractor
  CHANGELOG.md
  docs/build_and_release.md
  docs/creating-a-t-engine.md
  docs/metadata-extract-embbed.md
  docs/transform-services.md
Labels: PR: unreviewed

#1832 Print *deploy_dir* content before upload to AWS (release job) [skip ci]
  .travis.yml
Labels: PR: reviewed-approved

#1831 ACS-1077 fix pipeline image tag
  .travis.yml
  tests/pipeline-all-amps/pom.xml
  tests/pipeline-all-amps/repo/pom.xml
  tests/pipeline-all-amps/share/pom.xml
Labels: PR: unreviewed

#1836 ACS-1043 : Camel upgrade to 3.7.0
  .travis.yml
  docker-alfresco/pom.xml
  tests/pipeline-all-amps/repo/pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: reviewed-approved

#1838 Fix Search TAS tests
  tests/environment/.env
Labels: PR: reviewed-approved

#1834 ACS-1110 replace fabric8 with docker-maven-plugin
  dev/dev-acs-amps-overlay/pom.xml
  dev/dev-tomcat/pom.xml
  dev/pom.xml
  distribution/pom.xml
  docker-alfresco/aws/pom.xml
  docker-alfresco/pom.xml
  docs/create-custom-image.md
  pom.xml
  scripts/travis/init.sh
  tests/pipeline-all-amps/pom.xml
  tests/pom.xml
  tests/tas-all-amps/pom.xml
Labels: PR: unreviewed

#1841 Feature/acs 247 relational query accelerator
  .travis.yml
  CHANGELOG.md
  docs/images/RefreshQuerySet1.png
  docs/images/RefreshQuerySet2.png
  docs/images/RefreshQuerySetNotStarted.png
  docs/images/RefreshQuerySetStarted.png
  docs/query-accelerator.md
Labels: PR: partially-approved

#1843 SEARCH-2662 Disable failing Elasticsearch tests.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: reviewed-approved

#1842 Fix TravisCI deploy options for the S3 Staging bucket upload [skip ci]
  .travis.yml
Labels: PR: unreviewed

#1849 The Single pipeline jobs should not have any commented out AMPs.
  pom.xml
  tests/pipeline-all-amps/repo/pom.xml
  tests/pipeline-all-amps/share/pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: reviewed-approved

#1845 [REPO-5474] Updated documentation in regards to node and aspects
  docs/query-accelerator.md
Labels: PR: reviewed-approved

#1850 REPO-5534 Make Query Accelerator config directory setup consistent
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j.properties
  docs/query-accelerator.md
Labels: PR: unreviewed

#1852 Acs 940
  docs/images/acs-aspects.png
  docs/images/acs-properties.png
  docs/query-accelerator.md
Labels: PR: unreviewed

#1853 Acs 940
  docs/query-accelerator.md
Labels: PR: unreviewed

#1855 Updated the API Explorer to the latest version
  pom.xml
Labels: PR: reviewed-approved

#1851 [SEARCH-2654]
  tests/environment/.env
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: reviewed-approved

#1856 ACS-1146 Replace *javax* dependencies with *jakarta* libraries
  distribution/pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-elasticsearch/pom.xml
  tests/tas-integration/pom.xml
  tests/tas-restapi/pom.xml
  tests/tas-sync-service/pom.xml
Labels: PR: unreviewed

#1846 Search-2658 fix Elasticsearch tests
  tests/environment/docker-compose-elasticsearch.yml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTests.java
Labels: PR: reviewed-approved

#1859 MNT-21817 Selectively disable renditions to avoid extra load
  docs/custom-transforms-and-renditions.md
Labels: PR: unreviewed
