Repository Alfresco/acs-packaging, pull requests merged in 2021-05, with the labels that each got.

#1935 added distribution-share module
  distribution-share/pom.xml
  distribution-share/src/assembly/share-distribution.xml
  distribution-share/src/main/resources/README.txt
  distribution-share/src/main/resources/alfresco-share-encryption/README.txt
  distribution-share/src/main/resources/web-extension-samples/custom-slingshot-application-context.xml.sample
  distribution-share/src/main/resources/web-extension-samples/share-config-custom.xml
  distribution-share/src/main/resources/web-extension-samples/smartfolders-amp-actions-config.xml
  distribution-share/src/main/resources/web-server/conf/Catalina/localhost/share.xml
  distribution/src/assembly/distribution.xml
  pom.xml
Labels: PR: unreviewed

#1936 SEARCH-2870: Disable Elasticsearch TAS tests as they are failing cons…
  .travis.yml
Labels: PR: reviewed-approved

#1939 SEARCH-2870: Re-enable Elasticsearch TAS Tests
  .travis.yml
Labels: PR: reviewed-approved

#1940 bump share 7.1.0-A2
  pom.xml
Labels: PR: unreviewed

#1941 ATS-912: Bump to ATS 1.4.0-A3 (T-Router 1.4.0-A3, T-Core 2.4.0, Shared-File-Store 0.14.1)
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#1942 Update elasticsearch connector to 3.0.0-RC1
  tests/environment/.env
Labels: PR: unreviewed

#1944 ACS-1560 Update AGS amp build configuration for compatibility with ACS and its release plugin [skip ci]
  pom.xml
Labels: PR: unreviewed

#1943 Feature/search 2839 reindexing e2e tests
  .travis.yml
  tests/environment/docker-compose-elasticsearch.yml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchAdminConsoleTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: reviewed-approved

#1949 SEARCH-2839 - fix intermittent build failure due to lack of output on sdtout
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/resources/log4j.properties
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: reviewed-approved

#1950 [SEARCH-2869]
  tests/environment/.env
Labels: PR: reviewed-approved

#1951 ATS-916 Bump T-Service->1.4.0
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#1952 Bump Sync Service from 3.3.3.1 to 3.3.4-A2
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#1954 Bump Sync Service from 3.3.4-A2 to 3.3.4-M2
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#1955 bump of share and salesforce
  pom.xml
Labels: PR: partially-approved

#1953 SEARCH-2903 Use "quay.io/alfresco/alfresco-content-repository" Docker…
  .travis.yml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
Labels: PR: reviewed-approved
