Repository Alfresco/acs-packaging, pull requests merged in 2021-11, with the labels that each got.

#2095 PRODSEC-4343 Build the MMT tool in alfreaco-community-repo so it picks up the latest libraries
  distribution-share/pom.xml
  distribution/src/main/resources/VERSIONS.md
  tests/tas-all-amps/pom.xml
Labels: PR: unreviewed

#2089 ACS-2168-elasticsearch-tag-support
  tests/environment/.env
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTagIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: unreviewed

#2082 SEARCH 2028 Adding e2e test for updating folder path
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: unreviewed

#2096 PRODMAN-440 Remove Glacier Connector AMP
  pom.xml
  tests/pipeline-all-amps/repo/dtas/dtas-config.json
  tests/pipeline-all-amps/repo/pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: reviewed-approved

#2101 DESKTOPAPP-782: Bump sync service from 3.4.0 to 3.5.0-A2
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2100 Python script to find the releases containing a fix.
  scripts/dev/find-fix.py
Labels: PR: unreviewed

#2102 Update find-fix.py to add -p option.
  scripts/dev/find-fix.py
Labels: PR: reviewed-approved

#2108 ACS-2167: Bump S3 Connector from 5.0.0-A1 to 5.0.0-M1
  pom.xml
Labels: PR: partially-approved

#2107 ACS-2235: Bump Azure Connector from 3.0.0-A1 to 3.0.0-M1
  pom.xml
Labels: PR: unreviewed

#2112 ACS-2250: Bump Azure Connector to 1.2.1
  pom.xml
Labels: PR: unreviewed

#2111 ACS-2172 Bump S3-connector-4.1.1
  .travis.yml
  pom.xml
Labels: PR: reviewed-approved

#2116 ACS-2210 Remove duplication of ESC version.
  tests/environment/.env
  tests/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializerESBasicAuth.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/MavenPropertyHelper.java
Labels: PR: reviewed-approved

#2117 ACS-2249 Add tests for basic term queries.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTokenisationTests.java
Labels: PR: reviewed-approved

#2118 ACS-2222 [release] 7.2.0-A7
  .travis.yml
Labels: PR: partially-approved

#2119 Update linkPoms to have ability to use git fetch.
  scripts/dev/linkPoms.sh
Labels: PR: reviewed-approved

#2120 [ACS-2240] Added test cases for moving files between sites and modify…
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchSiteIndexingTests.java
Labels: PR: unreviewed

#2123 Feature/acs 2240 e2e tas tests for site queries
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchSiteIndexingTests.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: unreviewed

#2122 ACS-2259 E2E tests for ES range queries.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
Labels: PR: unreviewed

#2124 ACS-2171 use package reference in test suite instead of classes
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/AlfrescoStackInitializerESBasicAuth.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/ElasticsearchBasicAuthTests.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-basic-auth-suite.xml
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: reviewed-approved

#2115 ACS-1998 Describe new T-Engine config elements may be used to modify the config
  docs/creating-a-t-engine.md
  docs/custom-transforms-and-renditions.md
Labels: PR: unreviewed

#2125 ACS-2297: Bump ACS Packaging (for S3 & Azure)
  pom.xml
Labels: PR: partially-approved
