Repository Alfresco/acs-packaging, pull requests merged in 2022-08, with the labels that each got.

#2274 ACS-3347 Upgrade to Java 17
  .travis.yml
  distribution/src/main/resources/VERSIONS.md
  scripts/travis/build.sh
  tests/tas-elasticsearch/pom.xml
  tests/tas-restapi/pom.xml
  tests/tas-sync-service/pom.xml
Labels: PR: unreviewed

#2276 MNT-23104: update S3 and Azure connectors
  pom.xml
Labels: PR: reviewed-approved

#2277 ACS-3347 Update recommended Java 17 version
  distribution/src/main/resources/VERSIONS.md
Labels: PR: partially-approved

#2280 ACS-3425: Extreme test instability, to be stabilized in this issue
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromSolrUpgradeTest.java
Labels: PR: reviewed-approved

#2281 Stabilize Opensearch Upgrade job test
  tests/environment/.env
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Elasticsearch.java
Labels: PR: reviewed-approved

#2282 Upgrade ES Connector
  tests/environment/.env
Labels: PR: partially-approved

#2284 DESKTOPAPP-1227: Bump sync service from 4.0.0-M2 to 3.7.1-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2285 Release process for ACS-7.3.0-A13
  .travis.yml
Labels: PR: reviewed-approved
