Repository Alfresco/acs-packaging, pull requests merged in 2022-07, with the labels that each got.

#2250 Bumped LIVE_INDEXING_TAG to 3.2.0-A3
  tests/environment/.env
Labels: PR: reviewed-approved

#2252 Feature/elasticsearch connector version update
  tests/environment/.env
Labels: PR: unreviewed

#2251 ACS-3269 Refactor Testcontainers initialisation to be in a new module.
  .travis.yml
  tests/pom.xml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchAdminConsoleTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchProximitySearchTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchTokenisationTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/AlfrescoStackInitializerESBasicAuth.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/initialReindex/ElasticsearchInitialReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchCMISPathTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchSiteIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchTagIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Config.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Elasticsearch.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromSolrUpgradeTest.java
  tests/testcontainers-env/pom.xml
  tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/EnvHelper.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/MavenPropertyHelper.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/SearchEngineType.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/TestDataUtility.java
Labels: PR: unreviewed

#2253 ACS-3254 Bump Alfresco SAML to 1.2.3-A1
  pom.xml
Labels: PR: partially-approved

#2256 ACS-3254 Bump SAML to 1.2.3-A1 for ACS 7.2.N
  pom.xml
Labels: PR: partially-approved

#2257 DESKTOPAPP-1148: Bump sync service from 4.0.0-M1 to 4.0.0-A2
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2260 More memory assigned for search engine test containers
  tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
Labels: PR: reviewed-approved

#2261 More memory assigned for TAS tests executions
  .travis.yml
Labels: PR: reviewed-approved

#2263 Use version of alfresco-digital-workspace from .env (2.7.0)
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2269 Updating Salesforce Alpha version (2.3.6-A2)
  pom.xml
Labels: PR: reviewed-approved

#2266 ACS-3236 Bump SAML to 1.2.3
  pom.xml
Labels: PR: partially-approved

#2268 ACS-3236 Bump SAML to 1.2.3
  pom.xml
Labels: PR: partially-approved

#2265 ACS-3236 Bump SAML to 1.2.3
  pom.xml
Labels: PR: partially-approved

#2267 ACS-3236 Bump SAML to 1.2.3
  pom.xml
Labels: PR: unreviewed

#2271 ACS-3342 Bump PostgreSQL to the latest 14.x
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2273 ACS-3344 Upgrade salesforce connector
  pom.xml
Labels: PR: partially-approved

#2254 ACS-3141 ACS-3140 Old ACS with Solr to Latest ACS with Elasticsearch upgrade test
  .travis.yml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/ACSEnv.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/ACSEnv52.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/BaseACSEnv.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Config.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromLegacyAcsUpgradeTest.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromSolrUpgradeTest.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/LegacyACSEnv.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/LegacyAcsUpgradeScenario.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/RepoHttpClient.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/UpgradeScenario.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Utils.java
Labels: PR: reviewed-approved

#2270 ACS-3306 Upgrade activemq to 5.17.1-jre11-rockylinux8
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed
