Repository Alfresco/acs-packaging, pull requests merged in 2022-01, with the labels that each got.

#2138 ACS-2412 Log files flooded with transformation option messages when misconfigured
  docs/custom-transforms-and-renditions.md
Labels: PR: unreviewed

#2139 SHA-2497 : Copy Image to dockerhub
  .travis.yml
  scripts/travis/copy_share_image_to_docker_hub.sh
Labels: PR: reviewed-approved

#2103 ACS-2217 add test on root node without wildcards
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
Labels: PR: reviewed-approved

#2141 DESKTOPAPP-853:Bump Sync service from 3.5.0-M1 to 3.5.0-A3
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2142 MNT-22696 update changelog
  CHANGELOG.md
Labels: PR: partially-approved

#2143 Feature/mnt 22696 replace renditions via restapi 71 n
  CHANGELOG.md
Labels: PR: partially-approved

#2140 ACS-2441 - adjust log levels for TAS-based ES tests
  .travis.yml
  tests/tas-elasticsearch/src/test/resources/log4j.properties
Labels: PR: reviewed-approved

#2145 ACS-2287: Bump Azure Connector to 3.0.0-A7 (from 3.0.0-A5)
  pom.xml
Labels: PR: partially-approved

#2146 Fix/add 71 n changelog updates
  CHANGELOG.md
Labels: PR: unreviewed

#2148 ACS-2286: Bump S3 Connector version to 5.0.0-A7.
  pom.xml
Labels: PR: partially-approved

#2149 Protect against exceeding Travis log limit by surpressing Downloading/Downloaded messages.
  .travis.yml
Labels: PR: partially-approved

#2150 MNT-22758 - Prepare hotfix release
  .travis.yml
  CHANGELOG.md
  pom.xml
Labels: PR: unreviewed

#2151 Bump sync-service from 3.5.0-A3 to 3.5.0-A4
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2152 ACS-2303 Upload license reports from acs-packaging release.
  .gitignore
  .travis.yml
  scripts/travis/prepare_staging_deploy.sh
Labels: PR: partially-approved

#2154 ACS-2303 Don't generate license information for TAS test code.
  tests/pom.xml
Labels: PR: partially-approved

#2156 ACS-2303 Generate distribution license CSV using wars and amps.
  scripts/travis/prepare_staging_deploy.sh
Labels: PR: partially-approved

#2157 ACS-2104: [release] 7.2.0-A23
  .travis.yml
Labels: PR: partially-approved

#2159 ACS-2278 ACS-2288 Include M2 releases of Azure and S3 connector.
  pom.xml
Labels: PR: partially-approved

#2162 ACS-2303 Ensure we copy the third party license report to the release bucket.
  scripts/travis/copy_ags_to_release_bucket.sh
  scripts/travis/copy_share_to_release_bucket.sh
  scripts/travis/copy_to_release_bucket.sh
Labels: PR: partially-approved
