Repository Alfresco/acs-packaging, pull requests merged in 2022-06, with the labels that each got.

#2239 DESKTOPAPP-1071: Bump sync service from 3.7.0 to 4.0.0-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2226 ACS-2805: Elasticsearch CMIS - test ORDER BY syntax
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
Labels: PR: unreviewed

#2237 ACS-2974 - 72N - Zero Downtime Search Service Upgrade Test for
  .travis.yml
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/basicAuth/AlfrescoStackInitializerESBasicAuth.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/config/DefaultImagesConfig.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/config/ImagesConfig.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/ACSEnv.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/AvailabilityProbe.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Config.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Elasticsearch.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/FromSolrUpgradeTest.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/RepoHttpClient.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/UpgradeScenario.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/upgrade/Utils.java
  tests/tas-elasticsearch/src/test/resources/org/alfresco/elasticsearch/upgrade/babekyrtso.pdf
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-from-solr-upgrade-suite.xml
Labels: PR: reviewed-approved

#2242 DESKTOPAPP-1059: Bump sync service from 4.0.0-A1 to 4.0.0-M1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2243 Update pom.xml
  pom.xml
Labels: PR: reviewed-approved
