Repository Alfresco/acs-packaging, pull requests merged in 2022-09, with the labels that each got.

#2289 DESKTOPAPP-1260: Bump sync service 4.0.0-M3
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2288 ACS-3463: AIS version update
  pom.xml
  tests/environment/.env
  tests/tas-integration/pom.xml
Labels: PR: unreviewed

#2291 Bump sync service 3.7.2 into acs-packaging
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2293 ACS-3402: update version of azure-connector to 3.0.1-A1
  pom.xml
  tests/scripts/checkLibraryDuplicates.sh
Labels: PR: reviewed-approved

#2295 HXCS-269 Update HelloWorld example
  docs/creating-a-t-engine.md
  docs/metadata-extract-embed.md
  docs/migrating-a-legacy-transformer.md
Labels: PR: reviewed-approved

#2296 DESKTOPAPP-1263: Bump sync service from 3.7.2 to 3.7.3-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2298 ACS-3522 Remove SAML from ACS bundle
  distribution/src/main/resources/VERSIONS.md
  docs/verify-the-amp-has-been-applied.md
  pom.xml
  tests/environment/docker-compose-all-amps-test.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/pipeline-all-amps/repo/Dockerfile
  tests/pipeline-all-amps/repo/dtas/dtas-config.json
  tests/pipeline-all-amps/repo/idp.jks
  tests/pipeline-all-amps/repo/pom.xml
  tests/pipeline-all-amps/share/pom.xml
  tests/tas-all-amps/pom.xml
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: partially-approved

#2303 Update transform-core, transform-service and AIS versions
  pom.xml
  tests/environment/.env
Labels: PR: unreviewed

#2304 ACS-3589 Add reporting script to more TAS jobs.
  .travis.yml
  tests/scripts/output_logs_for_failures.sh
Labels: PR: reviewed-approved

#2305 ACS-3488 Remove TestNG dependency to use upgrade from parent.
  tests/tas-cmis/pom.xml
Labels: PR: unreviewed

#2306 ACS-3448 Output expected and actual values for Elasticsearch queries.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
Labels: PR: partially-approved
