Repository Alfresco/acs-packaging, pull requests merged in 2022-02, with the labels that each got.

#2161 DESKTOPAPP-843:Bump Sync service from 3.5.0-A4 to 3.5.0
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2163 Use a new gen cert with 10y expirarion
  tests/pipeline-all-amps/repo/idp.jks
Labels: PR: reviewed-approved

#2167 Fix/build process 622 hf
  .travis.yml
Labels: PR: unreviewed

#2168 [release] 6.2.3-A4 Re-Enabled Media Management and bumped Media Manag…
  pom.xml
Labels: PR: unreviewed

#2171 [release][publish] Hotfix 6.2.2.22
  .travis.yml
  CHANGELOG.md
Labels: PR: reviewed-approved

#2173 OPSEXP-1194: multistagebuilds
  docker-alfresco/ags/Dockerfile
  tests/environment/alfresco-with-jolokia/Dockerfile
  tests/pipeline-all-amps/repo/Dockerfile
Labels: PR: reviewed-approved

#2169 ACS-2290 Validate the ACS version properties in community repo.
  scripts/travis/build.sh
Labels: PR: partially-approved

#2170 ACS-2503: Including Azure Blob in DAU design.
  docs/direct-access-urls.md
Labels: PR: partially-approved

#2174 ACS-2290 Improve version validation to include hotfix version too.
  scripts/travis/build.sh
  scripts/travis/build_functions.sh
Labels: PR: reviewed-approved

#2176 ACS-2576 Add possibility to override the es connector tag
  tests/environment/.env
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchReindexingTests.java
Labels: PR: reviewed-approved

#2175 ACS-2505 Docs for DAU version renditions
  CHANGELOG.md
  docs/direct-access-urls.md
Labels: PR: reviewed-approved

#2181 ACS-2476: [release] 7.2.0-A24 [skip tests] as they have just run
  .travis.yml
Labels: PR: partially-approved

#2172 ACS-409: Some configs to make Azure AMP application easier.
  dev/aliases
  dev/dev-acs-amps-overlay/pom.xml
  dev/dev-repo-amps-overlay/pom.xml
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco-global.properties
Labels: PR: partially-approved

#2182 ACS-2478: Experiment to force all amps test to inc Azure Connector
  tests/environment/docker-compose-all-amps-test.yml
  tests/tas-all-amps/custom-content-service-context.xml
Labels: PR: partially-approved
