Repository Alfresco/acs-packaging, pull requests merged in 2022-03, with the labels that each got.

#2183 ACS-2589 / ACS-2590: Include M3 releases of Azure and S3 connector (targeting ACS 7.2.0-A24 or higher)
  pom.xml
Labels: PR: partially-approved

#2184 Feature/acs 2562 disallow secure comms none
  dev/dev-acs-amps-overlay/pom.xml
  dev/docker-compose.yml
  tests/environment/.env
  tests/environment/docker-compose-aims.yml
  tests/environment/docker-compose-all-amps-test.yml
  tests/environment/docker-compose-cmis-tests.yml
  tests/environment/docker-compose-email-tests.yml
  tests/environment/docker-compose-integration-tests.yml
  tests/environment/docker-compose-minimal.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/environment/docker-compose-rest-api-tests.yml
  tests/environment/docker-compose-sync-service.yml
  tests/environment/docker-compose-with-ldap.yml
Labels: PR: partially-approved

#2185 DESKTOPAPP- 897: Bump sync service from 3.6.0-A1 to 3.6.0-A2
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2186 ACS-2307 Update SS/IE to 2.0.3-RC4
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2187 ACS-2591: Updated azure connector version to 3.0.0
  pom.xml
Labels: PR: partially-approved

#2188 ACS-2307 Update IE/SS to 2.0.3-RC5
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: partially-approved

#2190 ACS-2592: Updated S3 connector version to 5.0.0
  pom.xml
Labels: PR: partially-approved

#2193 Updating Salesforce Version to 2.3.4
  pom.xml
Labels: PR: reviewed-approved

#2198 Build should not go red after each release - a test too far
  scripts/travis/build.sh
Labels: PR: unreviewed

#2199 ACS-2749: Replaced straight charAt usage
  tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
Labels: PR: partially-approved
