Repository Alfresco/acs-packaging, pull requests merged in 2022-10, with the labels that each got.

#2311 ACS-3670/ACS-3672: Include A1 releases of Azure and S3 connectors
  pom.xml
Labels: PR: partially-approved

#2312 Enable REST API TAS tests with AIMS
  .travis.yml
Labels: PR: partially-approved

#2314 Bump sync service from 3.7.2-A1 to 3.7.2-A3
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2315 Bump sync service from 3.7.3-A3 to 3.8.0-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2316 ACS-3674 bump elasticsearch connector.
  tests/environment/.env
Labels: PR: reviewed-approved

#2321 ACS-3673 Updated S3 connector version to 5.1.0
  pom.xml
Labels: PR: partially-approved

#2322 Update Azure connector version to 3.1.0
  pom.xml
Labels: PR: partially-approved

#2323 Upgrade to latest ATS components
  pom.xml
  tests/environment/.env
Labels: PR: reviewed-approved

#2324 DESKTOPAPP-1310: Bump sync service from 3.8.0-A1 to 3.8.0
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2325 Update AIS to 1.4.5
  pom.xml
Labels: PR: unreviewed

#2326 Upgrade to latest ES
  tests/environment/.env
Labels: PR: reviewed-approved

#2328 ACS-3660: [release][publish] 7.3.0
  .travis.yml
Labels: PR: partially-approved

#2329 ACS-3160 Open java.lang for Integration TAS tests
  tests/tas-integration/pom.xml
Labels: PR: reviewed-approved

#2327 APPS-1677 Remove unnecessary MAVEN_OPTS when building Share
  scripts/travis/build.sh
Labels: PR: partially-approved
