Repository Alfresco/acs-packaging, pull requests merged in 2022-04, with the labels that each got.

#2201 ACS-2752 Basic E2E test to run a CMIS query against ES.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/TestDataUtility.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/initialReindex/ElasticsearchInitialReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchPathIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchSiteIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchTagIndexingTests.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: partially-approved

#2202 ACS-2802 CMIS suffix query test.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
Labels: PR: partially-approved

#2203 ACS-2824 Check ACLs are respected by CMIS query.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCMISTests.java
Labels: PR: partially-approved

#2210 [release] 23.1.0-A3
  .travis.yml
Labels: PR: reviewed-approved

#2211 [release] 23.1.0-A4
  .travis.yml
Labels: PR: reviewed-approved

#2204 DESKTOPAPP-991: Bump sync service from 3.6.0 to 3.7.0-A1
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2208 ACS-2768 Automate update of t-router and t-engine references in repositories
  dev/.env
  dev/docker-compose.yml
  distribution/src/main/resources/VERSIONS.md
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
Labels: PR: unreviewed

#2213 ACS-2768 Fix of Automate update of t-router and t-engine references in repositories
  dev/.env
  dev/aliases
  scripts/dev/start-compose.sh
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2215 Feature/acs 2768 fix
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/AlfrescoStackInitializer.java
Labels: PR: reviewed-approved

#2212 Bump sync service from 3.7.0-A5 to 3.7.0
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved
