Repository Alfresco/acs-packaging, pull requests merged in 2022-12, with the labels that each got.

#2335 ACS-3160 Upgrade to Log4j2
  dev/README.md
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j.properties
  dev/dev-tomcat/src/main/tomcat/shared/classes/alfresco/extension/custom-log4j2.properties
  docs/creating-a-t-engine.md
  pom.xml
  tests/pipeline-all-amps/repo/Dockerfile
  tests/tas-all-amps/Dockerfile
Labels: PR: unreviewed

#2349 Feature/acs 4156 fix instabilities of elasticsearch reindexing tests
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchReindexingTests.java
Labels: PR: partially-approved

#2351 ACS-4142 Update salesforce-connector and desktop-sync versions
  pom.xml
Labels: PR: partially-approved

#2353 ACS-3871 Bump Azure Connector to 3.2.0-A1
  pom.xml
Labels: PR: reviewed-approved

#2358 Adding needed test file from community-repo
  tests/tas-restapi/src/test/resources/shared-resources/testdata/simpleEmailTemplate.ftl
Labels: PR: unreviewed

#2359 ACS-4188 Migrate tas tests to Log4j 2.x
  tests/tas-all-amps/src/test/resources/log4j.properties
  tests/tas-all-amps/src/test/resources/log4j2.properties
  tests/tas-cmis/src/test/resources/log4j.properties
  tests/tas-cmis/src/test/resources/log4j2.properties
  tests/tas-elasticsearch/src/test/resources/log4j.properties
  tests/tas-elasticsearch/src/test/resources/log4j2.properties
  tests/tas-email/src/test/resources/log4j.properties
  tests/tas-email/src/test/resources/log4j2.properties
  tests/tas-integration/src/test/resources/log4j.properties
  tests/tas-integration/src/test/resources/log4j2.properties
  tests/tas-restapi/src/test/resources/log4j.properties
  tests/tas-restapi/src/test/resources/log4j2.properties
  tests/tas-sync-service/src/test/resources/log4j.properties
  tests/tas-sync-service/src/test/resources/log4j2.properties
  tests/tas-webdav/src/test/resources/log4j.properties
  tests/tas-webdav/src/test/resources/log4j2.properties
Labels: PR: unreviewed
