Repository Alfresco/acs-packaging, pull requests merged in 2023-04, with the labels that each got.

#2432 ACS-4970 Bump Azure Connector to 3.2.0-A7
  pom.xml
Labels: PR: unreviewed

#2434 Investigate ES Upgrade test failures
  .github/workflows/ci.yml
Labels: PR: partially-approved

#2426 ACS-4932 Fix tag renaming.
  dev/aliases
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchTagIndexingTests.java
Labels: PR: unreviewed

#2435 Migrate to GHA
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .travis.yml
  docs/build_and_release.md
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/copy_ags_to_release_bucket.sh
  scripts/ci/copy_share_image_to_docker_hub.sh
  scripts/ci/copy_share_to_release_bucket.sh
  scripts/ci/copy_to_release_bucket.sh
  scripts/ci/init.sh
  scripts/ci/maven_publish.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare_staging_deploy.sh
  scripts/ci/source_clear.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/dev/newReleaseBranch.sh
  scripts/dev/prepare_buildx.sh
  scripts/dev/resetMasterVersion.sh
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/pipeline-all-amps/README.md
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/utils/AlphabeticalPriorityInterceptor.java
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: reviewed-approved

#2430 ACS-4462: Mutual TLS e2e test
  .github/workflows/ci.yml
  scripts/ci/generate_keystores.sh
  tests/environment/docker-compose-mtls.yml
  tests/pom.xml
  tests/tas-mtls/pom.xml
  tests/tas-mtls/src/test/java/org/alfresco/rest/MtlsRestTest.java
  tests/tas-mtls/src/test/java/org/alfresco/rest/mtls/TransformServiceTest.java
  tests/tas-mtls/src/test/resources/alfresco-mtls-context.xml
  tests/tas-mtls/src/test/resources/default.properties
  tests/tas-mtls/src/test/resources/mtls-suite.xml
Labels: PR: partially-approved

#2390 ACS-4021 Add E2E tests for path updates.
  tests/tas-elasticsearch/pom.xml
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/SearchQueryService.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/parallel/PathUpdateTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/parallel/RetryAnalyzer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/parallel/RetryAnnotationTransformer.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/utility/ElasticsearchRESTHelper.java
  tests/tas-elasticsearch/src/test/resources/alfresco-elasticsearch-context.xml
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-parallel-suite.xml
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
  tests/tas-elasticsearch/src/test/resources/test-suites/standard-elasticsearch-suites.xml
Labels: PR: unreviewed

#2437 GHA Workflow on master/release - Fix publish stage
  .github/workflows/master_release.yml
Labels: PR: reviewed-approved

#2436 ACS-4970 Bump AIS to 1.5.0-A4
  pom.xml
Labels: PR: partially-approved

#2440 [ACS-5005] Improve keystore/truststore generation for GHA
  .github/workflows/ci.yml
  scripts/ci/generate_keystores.sh
  tests/environment/docker-compose-mtls.yml
Labels: PR: reviewed-approved

#2441 ACS-4715 Re-enable three category indexing tests.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryIndexingTests.java
Labels: PR: partially-approved

#2442 Feature/acs 4462 hostname verification test
  .github/workflows/ci.yml
  tests/environment/docker-compose-mtls.yml
Labels: PR: unreviewed

#2444 bump sync service amp version to 3.9.0-A8
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2446 ACS-5068 Upgrade to SS 2.0.7-A5.
  tests/environment/.env
Labels: PR: partially-approved

#2445 ACS-5059 Bump Azure Connector to 3.2.0-A9
  pom.xml
Labels: PR: reviewed-approved

#2443 ACS-5025 Implement ARM64 daily health check
  .github/workflows/arm64.yml
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/pipeline-all-amps/repo/dtas/dtas-config.json
Labels: PR: partially-approved

#2450 ACS-5026 Add JIRA integration to the ARM64 health check
  .github/workflows/arm64.yml
  scripts/ci/jira/jira_integration.py
  scripts/ci/jira/requirements.txt
Labels: PR: partially-approved

#2456 bump sync service amp version to 3.9.0
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed
