Repository Alfresco/acs-packaging, pull requests merged in 2023-03, with the labels that each got.

#2406 DESKTOPAPP-1562: Bump Sync Service from 4.0.0-A11 to 4.0.0-M7
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: reviewed-approved

#2393 ACS-4139 Produce Multi-Arch Docker images
  .github/workflows/master_release.yml
  docker-alfresco/Dockerfile
  docker-alfresco/ags/Dockerfile
  docker-alfresco/ags/pom.xml
  docker-alfresco/aws/Dockerfile
  docker-alfresco/aws/pom.xml
  docker-alfresco/pom.xml
  docker-share/Dockerfile
  docker-share/ags/Dockerfile
  docker-share/ags/pom.xml
  docker-share/aws/Dockerfile
  docker-share/aws/pom.xml
  docker-share/pom.xml
  scripts/ci/build.sh
  scripts/dev/prepare_buildx.sh
  tests/pipeline-all-amps/pom.xml
  tests/pipeline-all-amps/repo/Dockerfile
  tests/pipeline-all-amps/repo/pom.xml
  tests/pipeline-all-amps/share/Dockerfile
  tests/pipeline-all-amps/share/pom.xml
Labels: PR: partially-approved

#2409 ACS-4139 Remove overwriting 'image.tag'
  docker-share/pom.xml
Labels: PR: partially-approved

#2411 ACS-4844 Temporarily force amps installation
  docker-alfresco/Dockerfile
  docker-alfresco/ags/Dockerfile
  docker-alfresco/aws/Dockerfile
  docker-share/aws/Dockerfile
  pom.xml
Labels: PR: unreviewed

#2410 ACS-4139 Copy multi-arch share image to dockerhub
  scripts/ci/copy_share_image_to_docker_hub.sh
Labels: PR: partially-approved

#2414 Acs 4844 restores strict amp validation
  docker-alfresco/Dockerfile
  docker-alfresco/ags/Dockerfile
  docker-alfresco/aws/Dockerfile
  docker-share/aws/Dockerfile
  pom.xml
Labels: PR: partially-approved

#2413 OPSEXP-2046 Add base build number to avoid conflicts with previous travis build number
  .github/workflows/master_release.yml
  scripts/ci/copy_to_release_bucket.sh
  scripts/ci/maven_release.sh
Labels: PR: reviewed-approved

#2415 ACS-4139 Temporarily disable multi-arch for pipeline-all-amps images
  tests/pipeline-all-amps/pom.xml
Labels: PR: unreviewed

#2416 Revert "ACS-4139 Temporarily disable multi-arch for pipeline-all-amps…
  tests/pipeline-all-amps/pom.xml
Labels: PR: partially-approved

#2420 ACS-4842 Bump azure-connector to 3.2.0-A6
  pom.xml
Labels: PR: partially-approved

#2417 ACS-4818 Tests for wildcard queries.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchLiveIndexingTests.java
Labels: PR: unreviewed

#2412 Feature/acs 4023 update get /tags to support getting tags by name
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchGetTagsTests.java
Labels: PR: partially-approved

#2422 ACS-4911 Intermittent reindexing tests.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchReindexingTests.java
Labels: PR: partially-approved

#2421 ACS-4900 Fix publish job
  scripts/ci/copy_ags_to_release_bucket.sh
  scripts/ci/copy_share_to_release_bucket.sh
  scripts/ci/copy_to_release_bucket.sh
Labels: PR: partially-approved

#2425 ACS-4928 Bump AIS to 1.5.0-A1
  pom.xml
Labels: PR: reviewed-approved
