Repository Alfresco/acs-packaging, pull requests merged in 2023-02, with the labels that each got.

#2382 ACS-4155 CRUD for categories with ES.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryReindexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/ElasticsearchPathIndexingTests.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
Labels: PR: unreviewed

#2383 Increase the timeout for ES tests.
  .github/workflows/ci.yml
Labels: PR: reviewed-approved

#2384 ACS-3750 Improve branch detection in if conditions
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#2386 ACS-4515 Multivalued path queries.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryIndexingTests.java
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryReindexingTests.java
Labels: PR: unreviewed

#2389 ACS-4620: Temporarily disabling ES vs. Oracle E2E tests.
  .github/workflows/ci.yml
Labels: PR: partially-approved

#2387 ACS-4154: Add category count to relevant CRUD endpoints for categories
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/ElasticsearchCategoriesCountTests.java
Labels: PR: partially-approved

#2388 ACS-4594: Re-enabling E2E test.
  tests/tas-elasticsearch/src/test/java/org/alfresco/elasticsearch/reindexing/CategoryIndexingTests.java
Labels: PR: partially-approved

#2391 ACS-4620 Restore ES vs. Oracle E2E tests
  .github/workflows/ci.yml
Labels: PR: partially-approved

#2394 ACS-3750 Fix cancelling workflow
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#2395 Investigate failures for ES&Oracle builds
  .github/workflows/ci.yml
Labels: PR: partially-approved

#2397 Remove unnecessary files from hosted runners to free up some disk space
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
Labels: PR: unreviewed

#2399 Bump Sync Service 4.0.0-A11
  pom.xml
  tests/environment/.env
  tests/environment/docker-compose-pipeline-all-amps.yml
Labels: PR: unreviewed

#2400 OPSEXP-1944 Switch to new acs license access & secret keys
  .github/workflows/ci.yml
Labels: PR: reviewed-approved

#2401 Use S3 pipeline secrets only where they are really needed
  .github/workflows/ci.yml
Labels: PR: reviewed-approved
