Repository Alfresco/acs-packaging, pull requests merged in 2023-01, with the labels that each got.

#2364 Bump Azure Connector to 3.2.0-A2
  pom.xml
Labels: PR: partially-approved

#2362 ACS-3843 Migrate to GHA
  .github/.ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  .gitignore
  .travis.yml
  docs/build_and_release.md
  scripts/ci/build.sh
  scripts/ci/build_functions.sh
  scripts/ci/cleanup_cache.sh
  scripts/ci/copy_ags_to_release_bucket.sh
  scripts/ci/copy_share_image_to_docker_hub.sh
  scripts/ci/copy_share_to_release_bucket.sh
  scripts/ci/copy_to_release_bucket.sh
  scripts/ci/init.sh
  scripts/ci/maven_publish.sh
  scripts/ci/maven_release.sh
  scripts/ci/prepare_staging_deploy.sh
  scripts/ci/source_clear.sh
  scripts/ci/update_downstream.sh
  scripts/ci/verify_release_tag.sh
  scripts/dev/newReleaseBranch.sh
  scripts/dev/resetMasterVersion.sh
  tests/environment/docker-compose-pipeline-all-amps.yml
  tests/pipeline-all-amps/README.md
  tests/tas-elasticsearch/src/test/resources/test-suites/elasticsearch-suite.xml
Labels: PR: partially-approved

#2371 Remove no longer needed test file
  tests/tas-restapi/src/test/resources/shared-resources/testdata/simpleEmailTemplate.ftl
Labels: PR: unreviewed

#2365 ACS-3843 Fix CI job name
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#2367 Update t-engine docs to better reflect problems and configuration override of core-aio
  docs/custom-transforms-and-renditions.md
Labels: PR: reviewed-approved

#2374 ACS-4378 Bump Alfresco Azure Connector to 3.2.0-M1
  pom.xml
Labels: PR: partially-approved

#2373 Improve logs to investigate DependaBot PRs failures
  .github/workflows/ci.yml
  scripts/ci/wait-for-alfresco-start.sh
Labels: PR: partially-approved

#2376 Bump upstream repo versions
  pom.xml
Labels: PR: partially-approved

#2377 ACS-3750 Bump alfresco-build-tools to v1.32.0
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#2378 Add support for running the tests with specified ESC and Repo images.
  .github/workflows/ci.yml
  tests/testcontainers-env/src/main/java/org/alfresco/tas/AlfrescoStackInitializer.java
  tests/testcontainers-env/src/main/java/org/alfresco/tas/SystemPropertyHelper.java
Labels: PR: partially-approved

#2380 ACS-4527 Fix upstream repo linking
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
Labels: PR: partially-approved

#2381 ACS-4455 Bump alfresco-build-tools to v1.33.0
  .ci.settings.xml
  .github/workflows/ci.yml
  .github/workflows/master_release.yml
  scripts/ci/init.sh
Labels: PR: partially-approved
